apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nodeapp
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: nodeapp
  template: 
    metadata: 
      labels: 
        app: nodeapp
    spec: 
      containers: 
        - 
          image: # docker container image created in Azure or other Cloud platform
          imagePullPolicy: Always
          imagePullSecrets: 
            - 
              name: nodeapp
          name: nodeapp
          readinessProbe: 
            httpGet: 
              port: 8080
